###-----------------------USERS-------------------------#
GET http://localhost:5148/api/users/

###
GET  http://localhost:5148/api/users/1

###
POST http://localhost:5148/api/users/create
Content-Type: application/json

{
    "name": "teste1",
    "releaseDate": "2026-08-31"
}

###
PUT http://localhost:5148/api/users/2
Content-Type: application/json

{
    "name" : "teste2"
}

###
DELETE http://localhost:5148/api/users/1



###-----------------Music-----------------
GET http://localhost:5148/api/musics/

###
GET http://localhost:5148/api/musics/1


###
POST http://localhost:5148/api/musics/create
Content-Type: application/json

{
    "name": "Just In The Wind",
    "artistIds": [1],
    "genreIds": [1,2],
    "albumId": 1,
    "releaseDate": "1989-04-12",
    "duration": "00:03:26"
}

###
PUT http://localhost:5148/api/musics/1
Content-Type: application/json
{
    
    "name": "Baby be mine",
    "author": "Michael Jackson",
    "genre": "Pop",
    "album": "Thriller",
    "releaseDate": "1982-04-30",
    "duration": "00:04:20"
    
}

###
DELETE http://localhost:5148/api/musics/1


#--------------PLAYLISTS------------------
###
GET http://localhost:5148/api/playlists/

###
GET http://localhost:5148/api/playlists/1

### Create playlist
POST http://localhost:5148/api/playlists/create
Content-Type: application/json

{
  "name": "teste444",
  "userId": 1
}

### Update name playlist 
PUT http://localhost:5148/api/playlists/1/edit
Content-Type: application/json

{
    "name": "sinta a paz"
}

### Add music in playlist
PUT http://localhost:5148/api/playlists/3/add/2



###
DELETE http://localhost:5148/api/playlists/1


### -----------------ALBUMS-----------------
GET http://localhost:5148/api/albums/

###
GET http://localhost:5148/api/albums/1

###
POST http://localhost:5148/api/albums/create
Content-Type: application/json

{
    "name": "Album Teste",
    "artistId": 1,
    "releaseDate": "2026-08-31"
}

###
PUT http://localhost:5148/api/albums/1/edit
Content-Type: application/json

{
    "name": "Album Teste Editado",
}

###
DELETE http://localhost:5148/api/albums/1




###-----------------ARTISTS-----------------
GET http://localhost:5148/api/artists/

###
GET http://localhost:5148/api/artists/1

###
POST http://localhost:5148/api/artists/create
Content-Type: application/json

{
    "name": "Artist Teste",
    "releaseDate": "2026-08-31"
}

###
PUT http://localhost:5148/api/artists/1/edit
Content-Type: application/json

{
    "name": "Artist Teste Editado",
}

###
DELETE http://localhost:5148/api/artists/1



###-----------------GENRES-----------------
GET http://localhost:5148/api/genres/

###
GET http://localhost:5148/api/genres/1

###
POST http://localhost:5148/api/genres/create
Content-Type: application/json

{
    "name": "Genre Teste"
}

###
PUT http://localhost:5148/api/genres/1/edit
Content-Type: application/json  

{
    "name": "Genre Teste Editado"
}

###
DELETE http://localhost:5148/api/genres/1

